version: '3.3'
services:
    mariadb:
        image: mariadb:10.3
        restart: always
        volumes:
            - ./docker/mariadb:/var/lib/mysql
            - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: 123456

    nginx:
        build: ./docker/nginx
        ports:
            - "8080:80"
        volumes:
            - ./docker/logs/nginx:/var/log/nginx
            - ./:/var/www/store
            - ./store:/var/www/store
        depends_on:
            - php

    php:
        build: ./docker/php-fpm
        image: php:7.2-fpm
        volumes:
            - ./:/var/www/store
            - ./store:/var/www/store

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
        container_name: 'store_elastic'
        environment:
          - discovery.type=single-node
          - "discovery.zen.ping.unicast.hosts=elasticsearch"
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        ports:
          - 9200:9200
          - 9300:9300
        working_dir: /app
        volumes:
          - ../:/app
          - ./docker/elasticsearch:/usr/share/elasticsearch/data
          - ./docker/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

