version: '3.3'
services:
    mariadb:
        image: mariadb:5.5
        restart: always
        volumes:
            - ./docker/mariadb:/var/lib/mysql
            - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: 123456

    nginx:
        build: ./docker/nginx
        ports:
            - "8080:80"
        volumes:
            - ./docker/logs/nginx:/var/log/nginx
<<<<<<< HEAD
            - ./:/var/www/store
=======
            - ./store:/var/www/store
>>>>>>> 47e8fac5df544a01135cd5c634fba588fa2690fd
        depends_on:
            - php

    php:
        build: ./docker/php-fpm
        image: php:7.2-fpm
        volumes:
<<<<<<< HEAD
            - ./:/var/www/store
=======
            - ./store:/var/www/store
>>>>>>> 47e8fac5df544a01135cd5c634fba588fa2690fd
